"""empty message

Revision ID: b9ed22aa98b7
Revises: 
Create Date: 2020-11-01 13:31:15.284933

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'b9ed22aa98b7'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('scenery',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False, comment='景区名称'),
    sa.Column('img_name', sa.String(length=50), nullable=True, comment='景区图片名称'),
    sa.Column('site', sa.String(length=100), nullable=False, comment='景区位置'),
    sa.Column('grade', sa.String(length=20), nullable=False, comment='景区等级(AAAAA)'),
    sa.Column('introduce', sa.Text(), nullable=False, comment='景区介绍'),
    sa.Column('open_time', sa.String(length=20), nullable=False, comment='开放时间'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    op.create_table('users',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('username', sa.String(length=50), nullable=False, comment='用户名'),
    sa.Column('password', sa.String(length=100), nullable=False, comment='用户密码'),
    sa.Column('permission', sa.Enum('0', '1'), nullable=False),
    sa.Column('register_data', sa.DateTime(), nullable=True, comment='注册时间'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('username')
    )
    op.create_table('ticket',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('name', sa.String(length=10), nullable=False, comment='门票名称'),
    sa.Column('type', sa.Enum('成人票', '儿童票'), nullable=False, comment='门票类型'),
    sa.Column('price', sa.Float(), nullable=False, comment='票价'),
    sa.Column('scenery_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['scenery_id'], ['scenery.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('userticket',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('phone', sa.String(length=20), nullable=False, comment='电话号码'),
    sa.Column('id_card', sa.String(length=20), nullable=False, comment='身份证号'),
    sa.Column('number', sa.Integer(), nullable=False, comment='购买数量'),
    sa.Column('ticket_id', sa.Integer(), nullable=True),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['ticket_id'], ['ticket.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('userticket')
    op.drop_table('ticket')
    op.drop_table('users')
    op.drop_table('scenery')
    # ### end Alembic commands ###
